language: php

php:
    - 5.6

env:
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*

cache:
    directories:
        - $COMPOSER_CACHE_DIR

before_script:
    - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}
